theme = "base16_transparent"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
shell = ["zsh", "-c"]

[editor.whitespace]
rebder = "all"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
# # Mac Alt-.
# "≥" = "repeat_last_motion"
# Mac Alt-` (no way to capture this; Alt-` is the same as `)
# # Mapping lower and upper to l and Alt-l
# "l"

"A-z" = "switch_to_uppercase"

[keys.select]
"A-z" = "switch_to_uppercase"
